version: "3"
services:
  uptick:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map container port 4000 to host port 4001
    expose:
      - "8000"
    environment:
      - NODE_ENV=production
      - MONGODB_DATABASE_URL=mongodb://mongodb:27017/uptick
      - MYSQL_DATABASE_URL=mysql://root:root@mysql:3306/uptick_6
    # volumes:
    #   - .:/app
    command: ["npm", "run", "dev"]
    depends_on:
      - mongodb
      - mysql

  mongodb:
    image: mongo
    container_name: mongodb345
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db  # Persist MongoDB data

  mysql:
    image: mysql
    container_name: mysql123
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: uptick_6
      MYSQL_USER: joyboy
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql  # Persist MySQL data
 
    
